### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by wagne342** [CNMAT/CNMAT-Externs#102]
@ramagottfried @equilet 

Here are some suggested additions to the readme:

1) Under the section about the MAC build there is no wget instruction for GSL or FFTW which will confuse noobs like me.

2) Under the Windows section:

**Right after...**

> **Note:**  although very tempting, ***do not install the GSL of FFTW packages through Cygwin***, we need to build these manually to work correctly (details below).

**Lets put something like the following:**

**Note:** Before you begin, be very sure that you have adminstrator privileges when running Cygwin.  Right click its icon, select 'Run as Administrator' and allow the program to make changes to your hard drive.

**Note:** As of this writing some of the following commands will fail if there is white-space in the user's account name.  For example, a user account path such as '/cygdrive/c/cygwin64/home/John\ Doe' will become truncated to just '/cygdrive/c/cygwin64/home/John' causing a fatal error in some of the builds.  As a temporary fix, you may rename your account name without spaces, e.g. '/cygdrive/c/cygwin64/home/John_Doe' to avoid errors.

**Comment by equilet** [comment]
"Under the section about the MAC build there is no wget instruction for GSL or FFTW which will confuse noobs like me."

reopening for this.
