### ISSUE TITLE
basic resonators~ lacks a help patch

### ISSUE THREAD

**Issue by adrianfreed** [CNMAT/CNMAT-Externs#107]
or it got moved somewhere???

**Comment by adrianfreed** [comment]
On reflection I prefer basic-resonators~ to be pulled from the repo and release. It is not owned by UC Regents or CNMAT and isn't required in the rest of the release. I will distribute it from my own github repo.

**Comment by adrianfreed** [comment]
Thanks for clarifications.
I am not sure what this is about: "Someone has removed the downloadable zips/tarballs associated with prior releases”

Are you referring to the ones that were served from the web site that was taken down (before github)?
Presumably these are on the archive disk for that site.

I am not offering to maintain basic-resonators~, but since it is my code it is better I host it on my own github.

In general it is a good idea to minimize 3rd party source in the CNMAT repositories. It produces IP entanglements and gets stale
without a discipline to update and test from the source repo. This is already a headache for you with FFTW and GSL. Their licenses
seem to contaminate and be in conflict with the UC license for the externals.

If you notice any more of my code with my personal copyright notice, please let me know. I remembering pulling some old code
and putting it into resdisplay, for example.

**Comment by equilet** [comment]
OK, will do
