### ISSUE TITLE
assist_string() no longer supported

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-Externs#119]
I'm getting this error in the Max window for Max 8:

> assist_string: function no longer supported

I that needs to be done some other way.

**Comment by equilet** [comment]
Can you give us more information about the circumstances that bring this error about?

**Comment by mzed** [comment]
1) Open Max 8.0.3 (this might be the problem)
2) Make a new patcher
3) Make a harmonics~ object
4) Errors in the Max window.

Errors also repeat when mousing over inlets/outlets

Not a problem with resonators~ or sinusoids~

**Comment by equilet** [comment]
Thanks - will investigate.

**Comment by equilet** [comment]
I can implement some quick fixes for any occurrences of [this issue(https://cycling74.com/forums/how-to-replace-the-function-assist_string) very soon, including a forthcoming update.

**Comment by equilet** [comment]
This will be fixed in the upcoming release (https://github.com/CNMAT/CNMAT-Externs/commit/10376011e3a225dc718d1a4c42436b065c815ceb).
