### ISSUE TITLE
granubuf~ missing in distro

### ISSUE THREAD

**Issue by thneuhaus** [CNMAT/CNMAT-Externs#120]
granubuf~is missing in the latest distro. At Github it says "moved to src/", but could not find it there.
It is on the CNMAT-Externals object List (Issue #91 as of Jan 7 2018)

**Comment by ramagottfried** [comment]
hi @thneuhaus, actually granubuf~ was only released for a short period of time some years ago  -- I moved it to a private repository back in 2015, which is still available here: https://github.com/ramagottfried/tilde/releases

There's been a little discussion about adding it back in to the release, but at the moment it's not included. 

*That said*, it's still an object I use a lot, so it's also on my list to do some updating to it in the near future. And actually, I see that I have some uncommitted changes in my local version... I'll update that soon.

I also have an odot/gen~ version of granubuf~ if you're interested.

all the best,
rama

**Comment by thneuhaus** [comment]
Dear Rama,

good to know, that its not dead ;-)

I used it in several Max7 Projects, but the old CNMAT Distribution (1.0.1) is not available for Max8 any more, so I have some problems migrating  my old projects.

Is there a precompiled Version that runs with Max8? The GEN Version, if it runs with Max8 would also be  fine, I guess.
(BTW: How does it compare performancewise, compared to the C++ Version? )

Best,

Thomas

**Comment by equilet** [comment]
@thneuhaus please continue the discussion regarding this object on [Rama's issue queue](https://github.com/ramagottfried/tilde/issues):  
Thanks again for your interest in CNMAT!
