### ISSUE TITLE
Analyzer~ crash

### ISSUE THREAD

**Issue by ndivuyo** [CNMAT/CNMAT-Externs#121]
Thank you for your amazing objects! However, [analyzer~] is causing crashes on my system. I can create the object and use it, however, if I try to edit or delete it or close a patch containing analyzer~, it crashes Max 8 100% of the time. I'n not sure if you'd have any insight or advice?

**Comment by equilet** [comment]
Analyzer~ is unsupported for the moment, but look out for an update soon.
