### ISSUE TITLE
all externals failing with Apple M1 chips 

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-Externs#127]
All CNMAT externals failing with Apple M1 chips. Reports are in... will discuss further in staff meeting

**Comment by EdmundCampion** [comment]
Ron Smith writes:  the objects that aren't being read in Max are working in my standalone applications on the M1 Mac that I created last year on an Intel chip Mac.

**Comment by wagne342** [comment]
I have made changes in the following branch and the project should now compile for Apple Silicon.

**Comment by wagne342** [comment]
There is a pre-release version for Apple Silicon posted [here](https://github.com/CNMAT/CNMAT-Externs/releases/tag/v1.0.4c).  

The above is fairly stable, but does have some known bugs that I am working to resolve.
• bpf crashes Max on object delete or close
• thread.join crashes Max when a messsage containing text is passed to thread.join
• bench~ is prevented from compiling

I am still working on the Windows version with current bug fixes.

**Comment by wagne342** [comment]
Please see the official v1.0.5 release available thru the package manager.  Closing for now, but please re-open if problem persists.
