### ISSUE TITLE
Windows build fails at OSC-Client.o

### ISSUE THREAD

**Issue by wagne342** [CNMAT/CNMAT-Externs#136]
The current build system under Cygwin fails for objects with dependencies in core gcc.  The "no such file" error on arpa/inet.h is due to its absence from  /usr/x86_64-w64-mingw32/sys-root/mingw/include.  arpa/inet.h *is* present at /usr/include, but apparently not compatible with mingw.  This must have worked in the past. I suspect changes in Cygwin packages have broken this.  Looking for a workaround.

`x86_64-w64-mingw32-gcc -DWIN_VERSION -DWIN_EXT_VERSION -U__STRICT_ANSI__ -U__ANSI_SOURCE -std=c99 -O3 -DNO_TRANSLATION_SUPPORT -msse3 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include -I../max-sdk-base/c74support/max-includes -Iinclude -I../max-sdk-base/c74support/msp-includes -Ilib -Ilib/Jehan-lib  -I../max-sdk-base/c74support/jit-includes -I../CNMAT-OSC/OSC-Kit -I../CNMAT-OSC/libOSC -I../CNMAT-SDIF/lib -Isrc/SDIF-Buffer -Iutility-library/search-path -I../libo -I../libomax -c -o build/Release/OSC-client.o ../CNMAT-OSC/libOSC/OSC-client.c
../CNMAT-OSC/libOSC/OSC-client.c:55:2: warning: #warning Congratulations on your good taste in choosing to compile Windows Max/MSP externals with GCC! [-Wcpp]
   55 | #warning Congratulations on your good taste in choosing to compile \
      |  ^~~~~~~
../CNMAT-OSC/libOSC/OSC-client.c:61:10: fatal error: arpa/inet.h: No such file or directory
   61 | #include <arpa/inet.h> // htonl
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:117: build/Release/OSC-client.o] Error 1
`

**Comment by wagne342** [comment]
@ramagottfried have you run into this before?

**Comment by maccallum** [comment]
@wagne342 I've moved all my Windows dev over to MSYS2. I'm not sure if it'll fix this issue, but it fixed a number of other build issues I was having a while back.

**Comment by wagne342** [comment]
I've tried building on Msys as well, but it doesnt support certain socket
programming headers required by some of our objects (the ones causing the
above error, in fact), so several objects with those dependencies can't be
built with it unless we do some major/minor surgery on some of the older
dependencies. I suspect this is why Cygwin was chosen in the first place.
It provides POSIX wrappers that allow imports of arpa/.. headers and a few
others that mingw doesn't support. But now this is precisely where Cygwin
is failing. Msys is clearly the better option if we could make it work.

**Comment by maccallum** [comment]
Just to make sure, you tried MSYS2, and not MSYS, right?

**Comment by wagne342** [comment]
@maccallum nearly certain I used MSYS2, but will check tomorrow morning when I get back to that machine. The root issue is the lack of support for the following headers in MSYS2:

arpa/inet.h
winsock2.h
...and upstream dependencies in /sys

https://packages.msys2.org/search?t=pkg&q=arpa%2Finet.h

**Comment by ramagottfried** [comment]
hi @wagne342 I'm not sure it was quite a while back, but I do see that I merged a pull request that added the arpa/inet.h include >> [link](https://github.com/CNMAT/CNMAT-OSC/commit/cbc80b8721946dc547015f69bfa8390222c2eb60#diff-85af38813e6e723e879655eccbdbf8956014312263e31c8f8348fc24d0eaa08eR61) -- Adrian gave the approval for the merge request, but I didn't test it myself. Maybe try rolling back the merge and see if it fixes the problem? then we should probably re-add the pull request as per Adrian's wishes -- but maybe it needs some testing first, not sure.

**Comment by wagne342** [comment]
Found the problem. The import added in the last merge to CNMAT-OSC is causing the problem. I have addressed it there. Now works on all platforms.
