### ISSUE TITLE
roughness.maxhelp dependency

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#17]
roughness.maxhelp has an instance of fiddle that we need to replace.  Presumably, analyzer~ may work, although I'm assigning this to John as he built that help patch a specific way.  This is a tiny detail that might be knocked out in minutes.

**Comment by equilet** [comment]
@maccallum is there any reason we can't use the 2nd to rightmost outlet of `analyzer~` for this help patch (or similar)?  I know that the analysis discussed in your paper comes from a different algorithm, but I suppose I am hoping one can assess roughness from any list of sinusoidal components...

**Comment by maccallum** [comment]
Try it and compare the results to fiddle~, they should be similar as analyzer~ uses some of fiddle~’s code. Yes, any analysis that produces sinusoidal components should work, and fiddle~ is there for compatibility with the paper. Ok with me to change to analyzer~.
