### ISSUE TITLE
Build release of externs for windows and Mac and tell Adrian

### ISSUE THREAD

**Issue by adrianfreed** [CNMAT/CNMAT-Externs#21]
This externs repo is now public. Please build and test externs and bundle up releases for windows and Mac and let me know when this is done so I can change the CNMAT website download links.
If there are build problems please bundle up the latest  solid release we are using in the classes for example.

**Comment by sone** [comment]
Are there any plans to release CNMAT externals for Windows 64bit? I would help/test if desired.

**Comment by equilet** [comment]
Hi @sone  - yes, there are, and the release date is approaching quickly.
Please email me for further details at jlubow@berkeley.edu if you're interested.
