### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jamiebullock** [CNMAT/CNMAT-Externs#26]
Hi,

A number of GPL libraries (FFTW, GSL) are listed as dependencies of CNMAT-Externs.

I couldn't find an "overall" license for CNMAT-Externs, but individual .c files suggest a BSD-style license, which is incompatible with linkage to GPL libs.

Can you clarify the licensing situation here? Shouldn't the externs that link to GPL libraries actually be GPLv2 or some other compatible license?

**Comment by adrianfreed** [comment]
Thanks for pointing this out. I will look into it.
We may have to pull those externs that rely on FFTW, GSL

**Comment by equilet** [comment]
This has been addressed.
