### ISSUE TITLE
updates for help files

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#31]
order of operations:
=

open patch
select all
expose format palette
choose default from style menu
select name of object (or any other text objects that you are going to change the attributes of), and choose "clear style" from the style menu
select name of object and make it 24pt bold

remove panels
remove copyright
remove segmented patchcords, unless they represent feedback
take out links 
take out credits

spacing of objects

- organize by use - columns, group functionality
- make sure that important or core messaging is closest to the object
- use the distribute feature in Max to speed up placement

cnmat svg - no logo

check subpatchers
see also area:  use menu instead of many messages

alignment of text borders

make sure comments are near their relevant knitting

---
stretch goals:
- make helpfiles have tabs instead of subpatchers

**Comment by equilet** [comment]
should be done by Friday, July 3rd.

**Comment by equilet** [comment]
jeff:

- SDIF-buffer.maxhelp
- SDIF-fileinfo.maxhelp
- SDIF-info.maxhelp
- SDIF-listpoke.maxhelp
- SDIF-ranges.maxhelp
- SDIF-tuples.maxhelp
- peqbank~.maxhelp
- pitch~.maxhelp
- poly.bus~.maxhelp
- poly.send~.maxhelp
- polywave~.maxhelp
- printit.maxhelp
- randdist.maxhelp
- rbfi.maxhelp
- res-transform.maxhelp
- resdisplay.maxhelp
- resonators~.maxhelp
- roughness.maxhelp

ilya:

- 2threshattack
- accumulate~.maxhelp
- analyzer~.maxhelp
- basicresonators~.maxhelp
- bdist.maxhelp
- bench.maxhelp
- bench~.maxhelp
- bessel.maxhelp
- bpf.maxhelp
- brightness~.maxhelp
- cnmatrix~.maxhelp
- decaying-sinusoids~.maxhelp
- deinterleave.maxhelp
- firbank~.maxhelp

rama:

- granubuf~.maxhelp
- gridpanel.maxhelp
- harmonics~.maxhelp
- interleave.maxhelp
- lcm.maxhelp
- list-accum.maxhelp
- list-interpolate.maxhelp
- loudness~.maxhelp
- midifile.maxhelp
- migrator.maxhelp
- oscillators~.maxhelp
- OSC-route.maxhelp
- OSC-schedule.maxhelp
- OSC-timetag.maxhelp
- OpenSoundControl.maxhelp

john:

- shot.ms~.maxhelp
- sin-transform.maxhelp
- sinusoids~.maxhelp
- slipOSC.maxhelp
- sphY.maxhelp
- thread.fork.maxhelp
- thread.join.maxhelp
- threefates.maxhelp
- trampoline.maxhelp
- trend-report.maxhelp
- vsnapshot~.maxhelp
- waveguide~.maxhelp
- whichthread.maxhelp
- xydisplay.maxhelp

**Comment by equilet** [comment]
@ilzxc @ramagottfried @maccallum

**Comment by ramagottfried** [comment]
hey guys, what did we decide for the font?
also, I don't think have the CNMAT svg resizable thing, is that in the repo sorry if I missed it.

**Comment by ramagottfried** [comment]
another issue: when you open help patches the documentation side bar opens by default -- I'm pretty sure this is reads a documentation XML file that we don't have yet.

**Comment by equilet** [comment]
Nothing to do about the font...  The default style takes care of this, and is C74's responsibility to maintain in the long term.  I believe the current default style yields Arial 12pt.

**Comment by equilet** [comment]
Here's a menu loader that might speed things up for people:

<pre><code>
----------begin_max5_patcher----------
429.3ocqTsrSqCCDccxWg0HwtPURCE3dWiPh0r7JTkaxTpAGaKaGHHD+6XON
oP4kJbYQckOY73yiL4w7LXkd.c.6ur+wxxdLOKifh.Yi6yfN9Pij6nxf9NT0
CEomn68Rz6evfoV.BkGJX.8ic0XUFtuYiPc8RK13SEVWNqrXbspj9a97YkaO
hpuSnBsltypQPQKw.8paN7nifsM2x6POZWhJ9JIQjxoC3wtQwAWd1Eme3ZgD
Ep05H+JhKD56QjBm2nuE2E0xUWGLqcv78FYz.mHty+PhC.7hTR1Dwj5IZaw0
hgkc5Vp54QzmxyiKE6YRnv6CVwz03wAxaAmwFRg0Lol2xNvMKblMnz7oQ1Wl
SmTNaQA63Sobp9zucNUs.1Sio52yALMZk2pk+OR9O0Qstn96q3ehfotCRg5s
yhD+h365BNcusYRMSyCrpsjrEcdgh6EZ0qJJFFrWTxFQaKpd87RqvEGgHwT9
g4w9xm2bUeBe9gzI4Vbi4Nz5FaIwjvaG2nswsmTPaEpzVpifEuSLUOMGBbaH
88gnu2lhpgiSeXAhClVUuXLoB27S4OCkjZCd
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
I'm actually going to fix up the SVG logo work myself on each of these, so don't worry about that part, guys.

**Comment by ilzxc** [comment]
I updated all of the files assigned to me (see recent updates). I also told John I would take over his if he needs extra time to focus on the build system. Let me know if that is the case...

**Comment by ramagottfried** [comment]
so, re: wavemaker.js -- is that staying in the repository for now?
there are better ways to do that i.e. odot, but I'm not sure if the Externs should have any odot in the help patches...

**Comment by ramagottfried** [comment]
ah, I remember now we talked about using the built in buffer~ table functions, I'll take a look at that.

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-Internal/issues/3
https://github.com/CNMAT/CNMAT-Externs/issues/18

**Comment by ramagottfried** [comment]
the buffer~ function doesn't do the same functions as wavemaker.js so isn't a drop in replacement. Odot would be, as discussed in CNMAT/CNMAT-Internal#3 but I'm not sure it's a good idea to include odot objects in the Externals release...  I guess wavemaker.js is more of a Depot tutorial, less necessary for the Externals help patches?  I'm inclined to simplify and take it out of the oscillator~ help patch.

**Comment by ramagottfried** [comment]
@equilet can you take care of gridpanel?

**Comment by adrianfreed** [comment]
we don't want a drop in replacement in the help patch - just the bare minimum.

wavemaker in its various conceptions needs to be part of revamped spectral tutorials.

I would like to get to revamping those when this rounds of new externals, Max 7, odot has stabilized.

**Comment by equilet** [comment]
@ramagottfried - sure
