### ISSUE TITLE
loudness~ not in master build target (also needs 64bit update)

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-Externs#36]
in case we want to include it in the release

**Comment by ramagottfried** [comment]
also needs to be updated to 64bit

**Comment by ramagottfried** [comment]
AFAIK analyzer~ has been updated but pitch/loudness/brightness are being phased out since analyzer~ does all of the same analyses.  if we wanted to re-release these objects I'd suggest adding `#ifdef` options in  the analyzer~ code to suppress different features (bark, partial tracking etc.)

**Comment by ramagottfried** [comment]
I propose we close this and say loudness is no longer part of the release since it is part of analyzer~

**Comment by maccallum** [comment]
I thought these objects like loudness~ were there for efficiency. If you’ve got some super CPU-hungry patch and all you need is loudness, you don’t want analyzer~ in there eating up a bunch of cycles computing measurements you don’t need. I’d say leave them in the release, but that’s just my 2c. At the very least, have it post a deprecated message and leave it around for a year to see if anyone in the community complains before you take things away from them.

**Comment by ramagottfried** [comment]
ah yeah, ok, maybe it makes sense to update them someday -- as far as I can tell it's been out of the release since 2013, so by now people are probably used to not having it... looks like it was commented out of the makefile here: https://github.com/CNMAT/CNMAT-Externs/commit/a661733f77ab840dfa8f9cc7d6601ba53fdd170a#diff-b67911656ef5d18c4ae36cb6741b7965R60
