### ISSUE TITLE
interleave should move to deprecated

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-Externs#37]
it even says in the help patch: "Don't use the interleave external! This is much better:"

**Comment by equilet** [comment]
It could be moved to a deprecated folder

**Comment by ramagottfried** [comment]
I propose we remove interleave since zl.lace and o.expr.codebox replace it.

**Comment by adrianfreed** [comment]
If you pull functionality from a release it is polite to provide an equivalent patch or workaround for people relying on it.

**Comment by equilet** [comment]
Keeping it in the main release for now.
