### ISSUE TITLE
resonators~ fails silently in 64-bit mode

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#38]
I found what I take to be a bug in resonators~ today:

1. load resdisplay.maxhelp helpfile, and remove args from resonators~ instances
1. select a part of the res model that initializes in this patch
1. turn audio on
1. click on float value, or hit 'p' to excite the model

result:  no sound
desired: triangle sound

regression:  I found that if I give resonators~ some arguments (for example, the ones in its help file), I am able to get it to consume the model and output audio

{
	"version" : "Version 7.0.4 (cbb83ff) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.10.4 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"eventinterval" : 1,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf"
}

**Comment by adrianfreed** [comment]
Did anyone test all the options for that one?

there are options double and smooth.
I am hoping that double is ignored and ALWAYS set.
single precision is a bad idea for the filter design equations and for running the filters.

smooth is an option and there are perform routines for the two cases: one when there is a signal wired to the inlet
and one without.

That means 4 possibilities have to be tested smooth/not smooth X inlet/no inlet.
Multiply that by 2 (32-bit vs 64-bit) and then by 2 again for the 2 platforms making a total of 16 possibilities to test.

Multiply that by 2 again for Max 6 and Max 7

**Comment by ilzxc** [comment]
I'll take care of this first thing tomorrow morning (I'm coming in
tomorrow).

**Comment by ilzxc** [comment]
Please note that the fix removes all routines working with `float`s -- everything is promoted to `double` (even the old float-based struct is gone). Tested with Max 6.1.9 (not 6.0.9 as said in commit -- typo) and 7.0.4 on Mac OS X only for now.

**Comment by equilet** [comment]
excellent, thanks!
