### ISSUE TITLE
*.js not included in distribution

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#4]
sinusoids~.maxhelp calls upon shepard.js, and we need it to be in the distribution.

**Comment by equilet** [comment]
the only remaining file is wavemaker, which has its own issue now.

**Comment by ramagottfried** [comment]
hey, not sure where the wavemaker issue is, but I removed wavemaker.js from the oscillators~ help patch, so I think it may not be in the repo now.
