### ISSUE TITLE
xydisplay: stupid little point + attrs

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#41]
"stupidlittlepoint" could be named something more useful.
also, this attr, and others sometimes jump to an enormous value for unknown reasons.

I'll try to work out a step of reproducible steps.

**Comment by equilet** [comment]
It'd be nice if the points could have a different color than the lines.  Sorry to FR, but I feel like it'd make the object's UI features more distinguishable.
Also, what is "Color"?

**Comment by equilet** [comment]
Another detail:  A UI attribute change does not call the paint method, only clicking in the object.

**Comment by ramagottfried** [comment]
* stupidlittlepoint seems to be gone now
* fixed paint method updates for attr changes
* fixed missing frame drawing
* removed unused Color attr field

I'm going to close this issue, but @equilet feel free to open a new one about your FR idea for different color points.
