### ISSUE TITLE
bench~ crash

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#43]
crashes m7 upon opening help file.

{
	"version" : "Version 7.0.4 (cbb83ff) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.10.4 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"eventinterval" : 1,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
}

**Comment by ilzxc** [comment]
Looking at the stack trace, it seems the culprit is resonators~ and not
bench~... This is my bad with the resonators~ update -- will have to spend
some time and get that fix in.
