### ISSUE TITLE
SDIF-fileinfo wrong for moanin.add.sdif

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-Externs#51]
SDIF-fileinfo is reporting 0 streams for moanin.add.sdif:

<pre><code>
----------begin_max5_patcher----------
404.3ocwS98SBCCDG+4s+JZ5yCbaff3alXLwm8QiwTV6fir0tz1gfD9e20qa
JBBRvG7k0bW+16GetaaBCnSUqDFJ4VxyjffMgAAnKmifV6.ZIaUVAyfxnkBi
gMSPi72YEqrn+qxgBAoTwjfrOiy6a3PNItSWEylMGjydUKxr97MYT+3HR5vw
tijTuUZ+XxKsuQVWppsEBKl4jVu.GymZ5hdClzEduN65JgO1T5tQAjcAIs0o
wtt.kRoNGaCCceh9iLvjwj6ifS.fahwNeH14dZjL4W6+bkzZf2wpuQ8gTI8S
p3jJYk9F8NMvJ9e3kT7VSgc.td59GenmasAj4JxbQQ0z5SwqwW6Qj+HN4W.V
54BrAitDfEcTnkbRngugV.x8+uC6Xm+uSRipVm0k0t4K4qllKLVPxrfRtiHW
Osin4.mKv665eNXXSKDHEh+wY54VO6kpiTOthN4BpGOtXUUKEZSaLwRoYEag
R6LGGglfzahycpVrD5z68vzMKT1lsoZseprZzPp+oJtPKqAb3E5x71vO.7WM
wXA
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
fixed, that was a weird one, it was working in debug mode but not in release -- turned out there was a function that was sometimes returning a non-existing value,... kind of amazed that it ever worked at all!
