### ISSUE TITLE
resdisplay outputs naked selection message

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#55]
...when a selection is made initially.  [selection] should always be packed with data

**Comment by equilet** [comment]
there's a workaround implemented in MMJD sdif editor to account for this currently... leaving this message here for the future when bug is fixed.

**Comment by equilet** [comment]
I've checked in a fix for this, which only suppresses output if user selects zero partials.

**Comment by adrianfreed** [comment]
Isn’t this a case of the nothing/nil/null/empty issue.

It is useful  when building an editor to know the user has selected nothing.

**Comment by equilet** [comment]
Yeah; I was debating on whether or not to include an identifier like `empty`, `<none>` etc.  The bang upon routing the selection message isn't quite explicit.
