### ISSUE TITLE
bench resolution on Windows

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-Externs#66]
added Windows support for bench, using the QueryPerformanceCounter() function.
however, I noticed that the resolution is not the same as the Mac version, so possibly it should be changed to use KeQueryPerformanceCounter instead.

see: https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx

**Comment by ramagottfried** [comment]
actually not sure, it looks like it should be the same resolution, leaving as is for now.

**Comment by equilet** [comment]
What is the status of this?

**Comment by ramagottfried** [comment]
ok, yes, I double checked and it looks like it's doing the right thing as detailed by the windows reference above.

I'm going to close this now.  as always, to anyone reading this, please reopen if you can test and find an issue.
