### ISSUE TITLE
should osc-related objects be moved to the odot repository?

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#73]
`osc-route`
`osc-schedule`
`osc-timetag`
`opensoundcontrol`

Thoughts?

**Comment by maccallum** [comment]
I don’t think so. The Max/MSP externs have much more traction than odot, and for long-time users who haven’t adopted (or noticed) odot, a move like this might just seem like they had disappeared. It might make some people download odot, but I’m not sure this type of coercion is ultimately useful.

If there was some discussion around CNMAT with some compelling points, I’d be interested to hear them.

One important thing to do at some point as the odot documentation is developing would be to state clearly that the odot objects are backwards compatible with these objects, and that these objects also serve as the reference implementation that the odot objects were designed against.
