### ISSUE TITLE
resonators~: crash with tellmeeverything

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#74]
I issue this message to resonators~, after booting from a prior crash, and get this crash.
https://gist.github.com/equilet/09e79e62ede19258c864182edaf2f775

I was previously attempting to send a large list into the object and benchmark the process using bench~, although that is possibly a red herring.

```
sys info

{
	"version" : "Version 7.3.4 (fcd0ee6) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.11.6 x86_64",
	"samplerate" : 44100,
	"iovs" : 2048,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"eventinterval" : 1,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "qt"
}

```

Patch:

<pre><code>
----------begin_max5_patcher----------
3047.3oc6bktbhijD921OEJH1+gGZU5DM6eVygMXCFvGXCytgCcTBjstPpvb
LwLuO6qw9jskN3P1RXYij83ocGcCzUIoLyOkUVY9Ukzue3AEjrlCcKP7qD+F
wAG76GdvA9M40vAg++CJXHNWVWz0+vJXBmYI8PgiB5BAmi7a1lXDzD5Hhfq5
RSwuC7A+KrzqZT0xDYJZ.865XGMQ8U8XMEoCQnE1v.soPAh+SXWtnE5Amw1W
FWsk9MBnJQF1r4TCMS7UwWSAaZL3ZGoUaQj7XMyQ26.kQARjkgDekH3YJQJP
J.nNhfqrWCTXArVW7OOnSH.EhPXERSG9DzwUyxbKobPAQa6sZ9fsNEOX8AK+
KD+QqaRyLnI50M4.eRa04yrtUQGr1ivp9Tm.jYdYtBatLVJPGyoZ9pRPi+wg
qToMFru45+AWfoyTlbiohcDFoaI+Hz+9H4pFsrglZl1NPWnIRDEpYq6VApJN
UGce72gh1upnLLwSNVujCJLxQSwxzSIhfydMuRb+FAv2Z.QLF+ivTzNlSF6h
hwjD5zEajSckDc7tMHE3GRspSjkkdztVed5PUTX21ZllOCEQV1I2oi1nw63b
krvcZrqqseOt2O0Ln26wCdQ26J9TTzFIpqGNZN5ketnolAdjLRK3V.E45Ngl
hXCcrqriktdD6MnmmhoGErGrLbllBZruf11Y.e3Z1qbhJr9trh1HnKJZaHwQ
tQa4EwEvMMUJbD58HngstW7nHGPj3caObb63dQZeWw+hFCzQzTQQyEQL0TS0
xw.aprDzraeraETjgd6NR1kO9fiGsU.xD.ijCTlXvxXBXRsUOwDzDPx6OVih
oDKKk.fG+aZZ+vl9C+Vcx+wgGt5GG8gf7.7+DRB5Y96.zyWtDKFsYDJAHYKS
68aZ9OcjGPRR.XIIISB6Y+6.1yFLCCOcIN1x7r3bE.re3Xusn7iXu7f+lDby
sOvcFB0zIB0fTA0BkKQA.b33K7bez.sDAcRvK+d.uRhli77ni78Gh2Mcpfbx
f7gyG31WMS.UYAuNtkBbJBXPte9eAIHSwt5yHhW1xv.mM7KT.MSE37sRBOS.
t.MOIjipvaCVR1GgLMvBE+5gkYI1rIsccMyjxWyWo75OdPy0Zpi7JWlUdUDQ
UNbBnHMy0Uw7aaFTSjVu82pVr5h+5ZAadqEfznEL4sVPkFsfNO0BtTdGwavU
9oEro0ufKO0Bl2hV.xKsf9snETwpEgMth2iBdk+pbePo92KhPNZRSQAgV1lH
m2TIoizsjD0CK3b8D+6p9zMEwd3F80+y.bKuXfil5q.Cb.V+bMvyo7SBCbzL
dlWvmeyA22bv8MGberbvU9aJ39jnfC7MCbeVLvQ8MAbefDvw9M+a4I+aeS+V
1S+FM42zu89neiF7M8aIUTe4zxxRhkzu+DKjVNVnA4IGKojzqx4rNjFffJm0
gzPAYdduvKTW5XZJGUBp2vHi7RG.uAc.7yFgaSMjfN+YLzpQI7NnUyUajoW2
DET0sDQuFKaOigljXdyiwosxaN5zLqZDK5Hk+GeN2wVpCqf+7KzdRjPPXCsb
YKfV9mE.khkwq3wLBPimR3e7mDfRwfx.92OJumbBS8l2Ulbj93DO8FpRe23z
TbHHDNPSLNdfDM7mWmf2+zL2xMaLtBbKU0HXQJHBmYGNG9FKKHHmtPRv4dmF
8pT.et2wXDx9W+wOlMaVIYSCQTI7XxGg5vEkfJS+Q6iu6GwgSoXgD7jfrkd.
O5dayTliV8QY7rGawk+t8gDdKKq.4Nhc4WBEKIaPgrbALG7NQSCnqq3H3KPy
+4+1AebD5hSMkGeuji0LWnCQ5wXu4pkslFjpNUL.eVuGpGqonDgm8zf8u4gu
gdxg0uIDL7UHi8jOyZrIQaQ4ph55SMH9e+WJRRrm1MUItDNBeBtkHNVWm3RO
N8cwsguyfyMINualWGj+X7Yo7mVfM3KZR58xmU0VSNNqkMQGmGzP2icWczlu
wEBhmzV4YFydrXeAErxPKDP1gPvhesUvAEQjX3b.BzgwcaV4wqNkTsxPyR3+
zsZyQ05c4w3et7DuFZ03Nuud5DyqJB89UsVFca1qdkFpkpvOpzfFUJUphZ2K
qUu1MzyFvIU2UqZ0JUOukbwhEmK0YVSj7jG623Bf0o8GN7xqpd6PoVitP8Fa
xgjfF2PeNPVscqIWeV0hWTVYRmyFR83C8bIqtf+pGolTahHbZeNnakl255d6
iK3jbE5rfaRmxiZT5RjwwlrcndjZfD4U2dkn948mVm5bU0ECl4zrhAYwh0LL
NancsVyKcg8ImT4zxPaKll8sd57K4UfMDaZzsd6q65p1xdfpRM0yG1iFb8Sk
OoYkYVV5Kd5pZtmun03pclOWVEozuVSyQMGZV8hVWV4tGo6IOtQG2g85cyIM
tt2UtCEmrDdm9S8fmUrmxBM9g0GTY.8XcCJIG6IyTtSl8h1KnOsV+5853zod
uqFMTbA3zqab7UULzGPW8DSZidUZzt2hIhfFSlXohUf4WzttRIlaJMYDyiCn
m0Xly4pSNSEYxLRT7gFpMTWHM+5k0aWi1Z5xNW1X3fIfS3NcPuJ8N+RIpRnw
hsOdPM2ajEOkTgT1cQoA0ZWGOJt0hZWsbde2186dVuEsf0Q2HclM67VhOoeS
awArl.ISkJcXgEmaMRxEM11sg5YTmeph8.d5wpOn0S5TYNTEdcs4BOnp2oAU
sdf6ZAF2uxr9KurQze3V7bq6HM5d2xoMJw5ZK2mYpA0UxCIGV13VEMkK5AGO
rKYwdmHdgF2npc5e1iWiuaKJo0Zzj521kuCnaQtoUYOkr40UtUiyX9Hj4oUw
2Kqd7xt8ojrb6odmickk8Gpqf5MkyZ9IE0nkJV8Dit7s6U75150k5Qe4odt1
kZdyCWUiwtqZyFExzvoRP7TX+4QD3zZHvQTIrP3psHpdQ6iuFGkcNQ3Z0dDg
rnIgDjPEOsE9HQ+ZbwX39KSDU+XnLBAqLF29EQc2PWowPcahvscfeBORK1L+
TbnD+eUPovEvhIDeD32uIdzsLi0foeOEN+BR5wFfC9TQPm6CV56sMtrbOqri
53X4CfnMO0XkYdwdVwac4D8OAt2AJlXQKLj6tnkcj8Wl7nxskQSQFcYJxlBX
mtTyacPHiy1AuCOnmWJWjx3xxBZoeUrigcM1Erqmx5h+WpSLxwZpMw+ZoN93
8rCerLVvj5cNbLePOpW2yKrXN1x6EzkTwbNX+CHAIw+.DWrqxeB6kt2bgWgD
1QGjXM29gSIGGm+uKwwWQvY3DeTky3f3txV1v3n7b8lSJvqaqGMWJuMwAII4
NILIEdI6hZjfwQzL9lKflb8WuK+jjMRlOQijlOSMxDh2ZZo4FqsC39zXa8MO
wdn+PX3UlbYhIGnqkoHxxwMVzZ+VA.cMWT9fZTuNpwIThkgkgGD7VDH6gtfx
KHvZEAZryz3fOguNT6uB1D7+RHOQLMyj.LJx8xeKOGmlBONlMYfmO3WxQ0n+
5DUKbBfrIpFbohnbrHBnPNMAFUYf2ZfENAFC6pOy3Eek9mk0dMbMEoC13z64
ZulX04.pOopyCeLZ7XsI2qNmlLgRJAjeQqOOD8X17PHUl9ip97DQSguJ0mux
2KnrS.GaNmAIgqgkEZbLPF+Wu7HWMO0V4QB.7eNIRx80IOxUv1mZdj.1uh4Q
tB5xt7HShRMDTW2.58HZt.4oDwAguK1y1SemxrdoBvxtdDmP7oG5qAQ2OzAv
wy2okgfxt2gkIr6J25EOvKf8TKGxs2WsIHHgLPPzTovhxBAI7Qgbowf.jY08
nWSRzTYfj3Sgf3x.4vkFCJxtNufkiRviwMH2kLU43kLUtKY.e7RlbujLKcJD
MSV3+vjpwDkyBIkl.jrzYkj.eHnWZFmy.xhfwBoURf8URkSyPc17vsOchNWh
xPml.ozYw3.pz3cREM.vV6ky8S1oI2AOJl2auHJxOp3J.g8veEj+hlRHOFpj
JQCh7VfJqlVDjlQofrHwPPpFTlEBJUIYjIYFx9QkrKaJFpykAizAoIWE.6KL
ofBtd1quGOg7rWaOO6U1yKec8j7qpmm+Z5AK4+3v+O3NkFWK
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
This doesn’t crash for me.

Aside from the fact that resonators~ is limited to 1024 resonances, the reason this doesn’t work is that [p generate] outputs 3 numbers, which means zl group has to be big enough to accommodate the number of times uzi will fire times 3.

**Comment by ramagottfried** [comment]
no crash here either

**Comment by equilet** [comment]
OK, I verified that I was using an old build.  Thanks for checking this out guys.
