### ISSUE TITLE
sdif-buffer: example sdif files not found 

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#78]
sdif-buffer.maxhelp:  These files are not on my system, nor do I think we have them stored in any repository.
I would like to take suggestions for 1 or two exemplary files to include in the help file, maybe one that is additive 1TRC and one that is resonance-based 1RES.

**Comment by EdmundCampion** [comment]
I have many of these. Will mail them.

**Comment by equilet** [comment]
OK, thank you!
