### ISSUE TITLE
testing:  build sys on windows

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#87]
WIN64: test build environment

replaces: https://github.com/CNMAT/CNMAT-Internal/issues/23

**Comment by ramagottfried** [comment]
actually we're not using VS now, so I think we can update this to be an issue to check if

**Comment by ramagottfried** [comment]
note: since we want to re-release midifile, we'll need to add java installation to the dev setup, downloading the java dev kit now (my internet is very slow at the moment).
