### ISSUE TITLE
cambio~ needed in externals download

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#9]
It is useful, and looking through the C code, easy to maintain.

Because this is a small issue, I'm assigning to you for the time being.
If this takes more than 20 minutes, please assign to Adrian.

Case reference:
http://cnmat.berkeley.edu/casetracker/case/13112
http://cnmat.berkeley.edu/casetracker/case/13154

Lubow to Campion:  "This is actually something to bring up with John - cambio~ is not the same as [snapshot~ 1] -> [change 0.]

In my estimation, to get this functionality at the bounds of the signal vector, you really need to be doing what cambio~ does. John, let me know if I’m wrong about this.

I think that we should continue to support cambio~ (even if it ends up being called something else), as it’s very useful for issuing control-rate changes that are bound to the signal vector w/r/t timing. It is also hanging on to the last few values for comparisons to detect the change with. All of this is expensive outside of the context of the perform routine.

It’s a matter of adding it back into the externals release, which shouldn’t be too hard, even if we want to rename it."

**Comment by ramagottfried** [comment]
added to windows makefile
