### ISSUE TITLE
rbfi: compat mode, inactive attrs and messages

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#96]
I'm looking around at all the patches I have on my machine throughout the years and I cannot find anything with the `compatmode` attr used.  If this is something that we can remove, we should, because I don't think it would have been used outside of the context of pedagogical patches at UCB.

Does anyone have thoughts on or experiences with this?

**Comment by adrianfreed** [comment]
don’t sweat the small stuff.

How are you all gonna test the hell out of the new recompiled bits before packaging things up?

**Comment by equilet** [comment]
Thanks Adrian - that's sage advice. I'm mainly just trying to tally everything that I find in here and move on as necessary. You'll note that what I seem to be important issues are compiled into the release milestone. :)On Jan 12, 2018 9:08 PM, Adrian Freed <notifications@github.com> wrote:don’t sweat the small stuff.

How are you all gonna test the hell out of the new recompiled bits before packaging things up?

**Comment by equilet** [comment]
Here are the attrs and messages that I believe to be inactive:  
1. bang
1. list
1. labelcolor
1. outputmode
1. pointcolor
1. selectedcolor
1. spaces (spaces seems active but maybe something that you would never want the user to edit?)

**Comment by adrianfreed** [comment]
hmmm
I can imagine uses for most of these.
Are some left over from the JS RBFI work John?

**Comment by maccallum** [comment]
I can’t say for certain why those seem to be inactive, but I can say that the design of the object changed quite a lot in the early days of that implementation, and I remember just leaving bits of code in there assuming that they’d be needed as the design continued to change. You can obviously just remove functions that have no body like rbfi_bang(), but like Adrian said, don’t sweat the small stuff.
